### ISSUE TITLE
Custom callback on UINavigationController

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-sdk#10]
Hi guys, is it possible to have a custom callback for the UINavigationItem? 

We need them because an example in our last project we are using a custom NavigatioManager and we cannot call the follow code directly:
```
present(, animated:, completion:)
dismiss(animated: , completion:)
```

**Comment by grimabe** [comment]
Hi @cikpis 

I am closing this issue as it is not about this repository but that one : 

https://github.com/usabilla/usabilla-u4a-ios-swift-sdk

Could you open another issue there and be more explicit about your request.
How do you want to present the view controller then ? 

Thanks
