### ISSUE TITLE
Scrolling issue on comment field

### ISSUE THREAD

**Issue by maartenaalbers** [usabilla/usabilla-u4a-ios-sdk#11]
Hi Guys,

We added the iOS SDK to our app and load a simple form onto it.
But when we try to add text to a comment field at the bottom of the form, were getting some weird scrolling behaviour. I added a movie (in a zip because GitHub won't allow it) to demonstrate the issue.
[Usabilla iOS Scroll issue.mp4.zip](https://github.com/usabilla/usabilla-u4a-ios-sdk/files/1003667/Usabilla.iOS.Scroll.issue.mp4.zip)

(using the 3.4.1 version of the SDK)

**Comment by grimabe** [comment]
Hi @maartenaalbers 
If you are using version 3.4.1 I assume this issue is meant to be created on our swift repository https://github.com/usabilla/usabilla-u4a-ios-swift

I am closing that one and let you create another one there.

Thank you

**Comment by maartenaalbers** [comment]
That page does not exists...

**Comment by maartenaalbers** [comment]
Moved it to: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/46

**Comment by grimabe** [comment]
you are right: wrong link but you go the right one now :-)
