### ISSUE TITLE
Color Changes

### ISSUE THREAD

**Issue by onurvarrrr** [usabilla/usabilla-u4a-ios-sdk#2]
Hi, I was checking https://github.com/usabilla/usabilla-u4a-ios-sdk/wiki/Changing-colors and tried 
 
```
UsabillaThemeConfig *config = [UsabillaThemeConfig sharedInstance];
config.headerColor = [UIColor whiteColor];
config.headerTextColor = [UIColor blackColor];
```

but this didn't make any changes in footer. Footer is using two colors (2) Header and (3)HeaderTextColor, but it seems HeaderTextColor not changing.See screenshots below

![ss1](https://cloud.githubusercontent.com/assets/4017312/13459554/2d973dea-e07d-11e5-87f0-3ca0195b8bad.png)
![ss2](https://cloud.githubusercontent.com/assets/4017312/13459555/2d98d362-e07d-11e5-87e4-aff064088d9a.png)
I guess"Powered By Usabilla" should be blue.

Thanks in advance.

**Comment by gPinato** [comment]
You're right. The SDK was using the wrong color.
It's fixed now, tomorrow I'll make an hotfix and publish a new version.

**Comment by gPinato** [comment]
I published the fix in the master branch. Update your pods and everything should be fine.
Let me know if you have any more issues.
