### ISSUE TITLE
Feedback level given on iOS is decremented by one when submitted

### ISSUE THREAD

**Issue by Wolfenberg** [usabilla/usabilla-u4a-ios-sdk#6]
When I give neutral, on the dashboard I see unhappy, when I give very unhappy then there's no rating at all.

On Android this doesn't happen.

Please, check ASAP.

I mean this rating:
<img width="306" alt="screen shot 2016-07-14 at 15 05 12" src="https://cloud.githubusercontent.com/assets/477746/16840348/7d4892ce-49d4-11e6-82d6-dc14fbe447ab.png">

**Comment by Wolfenberg** [comment]
@gPinato 1.6.6.6

**Comment by gPinato** [comment]
That is a bug that should have been resolved in the latest release. V 1.6.8 only contain bug fixes and minor improvements and you should be able to upgrade to it without any problem.

Could you try to do that and see if it fixes the problem?

**Comment by Wolfenberg** [comment]
Ah, I see. I missed the update.

**Comment by Wolfenberg** [comment]
Works, thanks!
