### ISSUE TITLE
UsabillaFeedbackForm.loadFeedbackForm freeze the current UIViewController

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-sdk#9]
Hi guys, after fetching the new version, 3.2.0, the form is showed properly but after dismiss Usabilla controller, the previous View is frozen.

Even commented the follow code the view is frozen:
```
func formLoadedCorrectly(_ form: UINavigationController, active: Bool) {
//    present(form, animated: true, completion: nil)
}
```

Here the code when we load Usabilla:
```
private func setupUsabilla() {
    // config the them form
    let themeConfig = UsabillaThemeConfigurator()
    themeConfig.customFont = Font.avenirLight.big
    // set the form
    UsabillaFeedbackForm.delegate = self
    UsabillaFeedbackForm.showCancelButton = true
    UsabillaFeedbackForm.loadFeedbackForm("xxxxxxxxxxxxxxxxxxxxxxx", themeConfig: themeConfig)
}
```

**Comment by grimabe** [comment]
Hi @cikpis 

In order to reproduce this behaviour, could you provide the code you use to show the form ? and/or provide a small test application to replicate the behaviour ?

Thanks

**Comment by cikpis** [comment]
Hi @grimabe, I updated the previous message.

**Comment by grimabe** [comment]
Hi @cikpis 

I am closing this issue as it is not about this repository but that one : 

https://github.com/usabilla/usabilla-u4a-ios-swift-sdk

Could you open another issue there ?
As we cannot replicate the bug: maybe it is related to your custom navigation controller your mentioning in #10.
Could you make a little demo project that you can share on github or send us by email ?

Thanks

**Comment by cikpis** [comment]
Issues opened in the other one. Sorry for the confusion.

Nope is not related to the custom navigation controller.
